# -*- python -*-
#
# $Header$
# Authors: James Chiang <jchiang@slac.stanford.edu>
# Version: genericSources-01-17-00

Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

libEnv.Tool('addLinkDeps', package = 'genericSources', toBuild='static')

if libEnv.get('CONTAINERNAME','') != 'ScienceTools_User':
    genericSourcesLib = libEnv.StaticLibrary('genericSources',
                                             listFiles(['src/*.cxx', 'src/*.c']))
else:
    genericSourcesLib = libEnv.StaticLibrary('genericSources',
                                             listFiles(['src/*.c', 
                                                        'src/Fi*.cxx',
                                                        'src/Gaus*.cxx',
                                                        'src/Iso*.cxx',
                                                        'src/Map*.cxx',
                                                        'src/P*.cxx',
                                                        'src/RadialSource.cxx',
                                                        'src/S*.cxx',
                                                        'src/Util.cxx']))

progEnv.Tool('genericSourcesLib')

test_genericSourcesBin = progEnv.Program('test_genericSources',
                                         'src/test/test.cxx')

progEnv.Tool('registerTargets', package='genericSources', 
             staticLibraryCxts=[[genericSourcesLib, libEnv]],
             includes=listFiles(['genericSources/*.h']),
             testAppCxts=[[test_genericSourcesBin, progEnv]],
             data = listFiles(['data/*'], recursive = True),
             xml = listFiles(['xml/*'], recursive = True))
