# -*- python -*-
# $Id$
# Authors: Nicola Omodei<nicola.omodei@pi.infn.it>
# Version: SpectObj-01-04-00
Import('baseEnv')
if baseEnv.get('CONTAINERNAME','') != 'ScienceTools_User':
    Import('listFiles')
    libEnv = baseEnv.Clone()

    progEnv = baseEnv.Clone()

    if baseEnv.GetOption('noroot') is False:
        SpectObjLib = libEnv.StaticLibrary('SpectObj', listFiles(['src/*.cxx']))
        libEnv.Tool('addLinkDeps', package = 'SpectObj', toBuild='static')
        progEnv.Tool('registerTargets', package = 'SpectObj',
                     staticLibraryCxts = [[SpectObjLib, libEnv]],
                     includes = listFiles(['SpectObj/*.h', 'eblAtten/*.h']),
                     data = listFiles(['data/*'], recursive = True))
